### PR TITLE
Relax version requirement for `tesla` package

### PR DESCRIPTION
**Pull request by marcandre**
This allows current version (1.4.2)

### CODE REVIEW

**Comment by marcandre** [comment]
A release would be very much appreciated.

Users of `wallaby` are currently forced to use an older `tesla` and/or can run into issues like expecting that the latest `wallaby` would install when [only an old version predating the use of `web_driver_client` will be installed](https://github.com/elixir-wallaby/wallaby/discussions/603).

**Comment by aaronrenner** [comment]
Thanks for this. I'm going to upgrade CI in the next day or two and then I'll merge this.

**Comment by marcandre** [comment]
Ping @aaronrenner

**Comment by grzuy** [comment]
> Thanks for this. I'm going to upgrade CI in the next day or two and then I'll merge this.

Hope this helps in any way: https://github.com/aaronrenner/web_driver_client/pull/68#issuecomment-883062853 :-)

**Comment by aaronrenner** [comment]
Thank you, @marcandre!

**Pull request merged**
